trigger:
- main
- develop

- feature/*
- release/*


variables:
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build:prod
  displayName: 'npm install and build'


- task: Npm@1
  condition: and(succeeded(), eq(variables.isMain, 'true'))
  inputs:
    command: 'publish'
    publishEndpoint: 'npm Automation'
  displayName: 'npm publish new version'